name: Linters

on: pull_request

env:
  FORCE_COLOR: 1
  BUNDLE_WITHOUT: "production"
  RAILS_ENV: test

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.4.4 # Match your local version

      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libsqlite3-dev
          gem install bundler
          bundle install

      - name: Setup Rubocop
        run: |
          [ -f .rubocop.yml ] || curl -o .rubocop.yml https://raw.githubusercontent.com/microverseinc/linters-config/master/ror/.rubocop.yml

      - name: Rubocop Report
        run: bundle exec rubocop --color
  nodechecker:
    name: node_modules checker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check node_modules existence
        run: |
          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set up a .gitignore file with this folder included on it to prevent this from happening in the future." && exit 1; fi
